---

# Travis file for Jenkins role

dist: 'trusty'
sudo: 'required'

services:
  - 'docker'

language: 'python'

env:
  matrix:
    - TOXENV='py27-ansible20'
    - TOXENV='py27-ansible21'
    - TOXENV='py27-ansible22'
    - TOXENV='py27-ansible23'

install:
  - 'pip install tox-travis'

script:
  - 'travis_wait 40 tox -e "${TOXENV}"'

notifications:
  webhooks: 'https://galaxy.ansible.com/api/v1/notifications/'
