---

# Tasks file for jenkins

- name: 'INIT | Load the OS specific varibles'
  include_vars: "{{ role_path }}/vars/{{ ansible_os_family }}.yml"


- name: 'INSTALL | Include debian install tasks'
  include: "{{ role_path }}/tasks/install_debian.yml"
  tags:
    - 'install'
    - 'jenkins'
  when: "{{ ansible_os_family == 'Debian' }}"


- name: 'CONFIG | Configure Jenkins user'
  include: "{{ role_path }}/tasks/manage_jenkins_user.yml"
  tags:
    - 'install'
    - 'jenkins'


- name: 'INSTALL | Ensure Jenkins is started'
  become: True
  service:
    name: "{{ jenkins_service_name }}"
    state: 'started'


- name: 'INSTALL | Configure jenkins launching settings'
  include: "{{ role_path }}/tasks/manage_startup.yml"
  tags:
    - 'configure'
    - 'jenkins'


- name: 'INSTALL | Restart jenkins if new version installed or startup change'
  include: "{{ role_path }}/tasks/restart_and_waiting_jenkins.yml"
  when: "{{
    jenkins_task_package_install.changed
    or jenkins_task_default_config.changed }}"


- name: 'INSTALL | Install and configure Jenkins CLI'
  include: "{{ role_path }}/tasks/manage_cli.yml"
  tags:
    - 'jenkins'
    - 'install'


- name: 'INSTALL | Install groovy scripts'
  include: "{{ role_path }}/tasks/manage_groovy_scripts.yml"
  tags:
    - 'jenkins'
    - 'install'


- name: 'CONFIG | Check if Jenkins v2 default administrative password file exists'
  become: True
  stat:
    path: "{{ jenkins_default_adm_passd_file }}"
  register: 'jenkins_administrative_password_file_test'
  changed_when: False


- name: 'CONFIG | Jenkins 2.0 default password protection workaround'
  include: "{{ role_path }}/tasks/jenkins_2_workaround.yml"
  register: 'jenkins_authentication_disabled'
  when:
    - "{{ jenkins_administrative_password_file_test.stat.exists is defined }}"
    - "{{ jenkins_administrative_password_file_test.stat.exists }}"
  tags:
    - 'configure'
    - 'jenkins'


- name: 'INSTALL | Manage plugins installations and upgrades'
  include: "{{ role_path }}/tasks/manage_plugins.yml"
  tags:
    - 'jenkins'
    - 'install'


- name: 'CONFIG | Include groovy main configuration'
  include: "{{ role_path }}/tasks/manage_main_config.yml"
  tags:
    - 'configure'
    - 'jenkins'


- name: 'CONFIG | Manage jenkins credentials'
  include: "{{ role_path }}/tasks/manage_credentials.yml"
  tags:
    - 'configure'
    - 'jenkins'


- name: 'CONFIG | Include groovy plugins configuration'
  include: "{{ role_path }}/tasks/manage_plugins_config.yml"
  when: "{{ jenkins_plugins }}"
  tags:
    - 'configure'
    - 'jenkins'
