---

# Tasks about plugins upgrade
#
- name: 'Get plugins should be upgraded'
  become: True
  become_user: "{{ jenkins_etc_user }}"
  get_jenkins_plugins:
    use_ssh_key: "{{ (jenkins_authentication_disabled is defined)
                        and (jenkins_authentication_disabled | skipped) }}"
    cli_path: "{{ jenkins_cli_path }}"
    deployment_ssh_key: "{{ jenkins_deployment_ssh_key }}"
    groovy_scripts_path: "{{ jenkins_groovy_scripts_path }}"
    url: "{{ jenkins_base_url }}"
  register: 'jenkins_list_plugins_for_upgrade'
  changed_when: False


- name: 'Upgrade plugins'
  become: True
  become_user: "{{ jenkins_etc_user }}"
  register: 'jenkins_tasks_upgrade_plugins'
  install_jenkins_plugin:
    name: "{{ item }}"
    state: 'latest'
    use_ssh_key: "{{ (jenkins_authentication_disabled is defined)
                        and (jenkins_authentication_disabled | skipped) }}"
    cli_path: "{{ jenkins_cli_path }}"
    deployment_ssh_key: "{{ jenkins_deployment_ssh_key }}"
    groovy_scripts_path: "{{ jenkins_groovy_scripts_path }}"
    url: "{{ jenkins_base_url }}"
  with_items: "{{ jenkins_list_plugins_for_upgrade.has_update }}"


- name: 'Restart Jenkins once all plugins upgraded'
  include: "{{ role_path }}/tasks/restart_and_waiting_jenkins.yml"
  when: "{{ jenkins_tasks_upgrade_plugins.changed }}"
