---

# Tasks about plugin management

- name: 'Manage plugins installation'
  include: "{{ role_path }}/tasks/manage_plugins_installation.yml"
  when: "{{ jenkins_manage_plugin_install }}"


- name: 'Manage plugins upgrade'
  include: "{{ role_path }}/tasks/manage_plugins_upgrade.yml"
  when: "{{ jenkins_manage_plugin_upgrade }}"


- name: 'Enable plugins'
  become: True
  become_user: "{{ jenkins_etc_user }}"
  register: 'jenkins_tasks_enable_plugins'
  enable_jenkins_plugin:
    name: "{{ item.name }}"
    use_ssh_key: "{{ (jenkins_authentication_disabled is defined)
                        and (jenkins_authentication_disabled | skipped) }}"
    cli_path: "{{ jenkins_cli_path }}"
    deployment_ssh_key: "{{ jenkins_deployment_ssh_key }}"
    groovy_scripts_path: "{{ jenkins_groovy_scripts_path }}"
    url: "{{ jenkins_base_url }}"
  with_items: "{{ jenkins_plugins }}"


- name: 'Restart Jenkins once all plugins enabled'
  include: "{{ role_path }}/tasks/restart_and_waiting_jenkins.yml"
  when:
    - "{{ jenkins_tasks_enable_plugins is defined }}"
    - "{{ jenkins_tasks_enable_plugins.changed }}"
