---

# Tasks about Jenkins plugins installation

- name: 'Get all plugin dependencies'
  become: True
  become_user: "{{ jenkins_etc_user }}"
  register: 'jenkins_tasks_dependencies_plugins'
  get_plugin_dependencies:
    name: "{{ item.name }}"
    cli_path: '/var/lib/jenkins/jenkins-cli.jar'
    use_ssh_key: "{{ (jenkins_authentication_disabled is defined)
                        and (jenkins_authentication_disabled | skipped) }}"
  with_items: "{{ jenkins_plugins }}"
  changed_when: False


- name: 'Install plugins'
  become: True
  become_user: "{{ jenkins_etc_user }}"
  register: 'jenkins_tasks_install_plugins'
  install_jenkins_plugin:
    name: "{{ item.1 }}"
    state: "{{ jenkins_plugins_state }}"
    cli_path: '/var/lib/jenkins/jenkins-cli.jar'
    use_ssh_key: "{{ (jenkins_authentication_disabled is defined)
                        and (jenkins_authentication_disabled | skipped) }}"
  with_subelements:
    - "{{ jenkins_tasks_dependencies_plugins.results }}"
    - 'output'


- name: 'Restart Jenkins once all plugins installed'
  include: "{{ role_path }}/handlers/restart_and_waiting_jenkins.yml"
  when: "{{ jenkins_tasks_install_plugins.changed }}"
