---

# Tasks about Jenkins plugins installation

- name: 'Get all plugin dependencies'
  become: True
  become_user: "{{ jenkins_etc_user }}"
  register: 'jenkins_tasks_dependencies_plugins'
  get_plugin_dependencies:
    name: "{{ item.name }}"
    use_ssh_key: "{{ (jenkins_authentication_disabled is defined)
                        and (jenkins_authentication_disabled | skipped) }}"
    cli_path: "{{ jenkins_cli_path }}"
    deployment_ssh_key: "{{ jenkins_deployment_ssh_key }}"
    groovy_scripts_path: "{{ jenkins_groovy_scripts_path }}"
    url: "{{ jenkins_base_url }}"
  with_items: "{{ jenkins_plugins }}"
  changed_when: False


- name: 'Install plugins'
  become: True
  become_user: "{{ jenkins_etc_user }}"
  register: 'jenkins_tasks_install_plugins'
  install_jenkins_plugin:
    name: "{{ item }}"
    state: "{{ jenkins_plugins_state }}"
    use_ssh_key: "{{ (jenkins_authentication_disabled is defined)
                        and (jenkins_authentication_disabled | skipped) }}"
    cli_path: "{{ jenkins_cli_path }}"
    deployment_ssh_key: "{{ jenkins_deployment_ssh_key }}"
    groovy_scripts_path: "{{ jenkins_groovy_scripts_path }}"
    url: "{{ jenkins_base_url }}"
  with_items: "{{
    (jenkins_tasks_dependencies_plugins.results | map(attribute='output'))
    | list | merge_array_list | unique }}"


- name: 'Restart Jenkins once all plugins installed'
  include: "{{ role_path }}/tasks/restart_and_waiting_jenkins.yml"
  when: "jenkins_tasks_install_plugins | changed"
