---

# Tasks about plugins upgrade
#
- name: 'Get plugins should be upgraded'
  become: True
  become_user: "{{ jenkins_etc_user }}"
  get_jenkins_plugins:
    cli_path: '/var/lib/jenkins/jenkins-cli.jar'
    use_ssh_key: "{{ (jenkins_authentication_disabled is defined)
                        and (jenkins_authentication_disabled | skipped) }}"
  register: 'jenkins_list_plugins_for_upgrade'
  changed_when: False


- name: 'Upgrade plugins'
  become: True
  become_user: "{{ jenkins_etc_user }}"
  register: 'jenkins_tasks_upgrade_plugins'
  install_jenkins_plugin:
    name: "{{ item }}"
    cli_path: '/var/lib/jenkins/jenkins-cli.jar'
    state: 'latest'
    use_ssh_key: "{{ (jenkins_authentication_disabled is defined)
                        and (jenkins_authentication_disabled | skipped) }}"
  with_items: "{{ jenkins_list_plugins_for_upgrade.has_update }}"


- name: 'Restart Jenkins once all plugins upgraded'
  include: "{{ role_path }}/handlers/restart_and_waiting_jenkins.yml"
  when: "{{ jenkins_tasks_upgrade_plugins.changed }}"
