---

# Role tests

- name: 'Converge | Prerequisites tasks'
  hosts: 'jenkins-docker-xenial'
  gather_facts: False
  tasks:
    - name: 'PREREQUISITES | APT | Do an apt-get update'
      become: True
      raw: 'apt-get update -qq'
      changed_when: False
    - name: 'PREREQUISITES | APT | Install python 2.7'
      become: True
      raw: 'apt-get install -qq python2.7'
      changed_when: False


- hosts: 'all'
  name: 'PREREQUISITES | SSH utils, curl and java'
  roles:
    - role: 'infOpen.openjdk-jre'
    - role: 'infOpen.openjdk-jdk'
  tasks:
    - name: 'PREREQUISITES | APT | Install SSH utils and curl'
      become: True
      apt:
        name: "{{ item }}"
        update_cache: True
        cache_valid_time: 3600
      with_items:
        - 'curl'
        - 'openssh-client'
      when: "(ansible_os_family | lower) == 'debian'"


- name: 'Converge | Main tasks'
  hosts: 'all'
  roles:
    - role: "ansible-role-jenkins"
